model_type: random_forest  # "linear_regression", "random_forest" or "gradient_boosting"

linear_regression_params: {}

random_forest_params:
  n_estimators: 100
  max_depth: 10
  random_state: 42

gradient_boosting_params:
  n_estimators: 100
  max_depth: 3
  learning_rate: 0.1
  random_state: 42

use_feature_selection:
  linear_regression: true
  random_forest: false
  gradient_boosting: false
