
feature_selection: 
  method: rfe

target_col:
  target_column: price
  to_feature_store: true

baseline_model_params:
  n_estimators: 100
  max_depth: 5
  random_state: 42

model_predict:
  model_path: data/06_models/champion_model.pkl
  columns_path: data/06_models/feature_columns.pkl

model_selection:
  hyperparameters:
    RandomForestClassifier:
      n_estimators: [100, 300]
      max_depth: [null, 10, 20]
      min_samples_split: [2, 5]

    GradientBoostingClassifier:
      n_estimators: [100, 200]
      learning_rate: [0.05, 0.1]
      max_depth: [3, 5]

model_training:
  model_type: ["random_forest", "gradient_boosting"]
  random_forest_params:
    n_estimators: 100
    max_depth: 10
    random_state: 42
  gradient_boosting_params:
    n_estimators: 100
    max_depth: 3
    learning_rate: 0.1
    random_state: 42
  use_feature_selection:
    random_forest: false
    gradient_boosting: false
  relevant_metric: "test_rmse"

